# Generated by Django 5.1.3 on 2024-12-07 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=50, null=True)),
                ('password', models.TextField(max_length=50, null=True)),
                ('specialization', models.TextField(max_length=50, null=True)),
            ],
        ),
    ]
